# Generated by Django 4.1.7 on 2023-04-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_ticket_photo'),
        ('authentication', '0006_userfollows_unique_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_pic', to='feed.avatarpic'),
        ),
    ]
