# Generated by Django 4.1.7 on 2023-04-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_photo_ticket_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
