# Generated by Django 4.1.7 on 2023-04-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_delete_userfollows'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarPic',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.photo')),
            ],
            bases=('feed.photo',),
        ),
        migrations.CreateModel(
            name='TicketPic',
            fields=[
                ('photo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.photo')),
            ],
            bases=('feed.photo',),
        ),
    ]
