# Generated by Django 4.1.7 on 2023-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_avatarpic_ticketpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.ticketpic'),
        ),
    ]
